# LEF AI v1 Docker Compose Configuration
# Removed obsolete version attribute

services:
  lef_core:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BUILDKIT_INLINE_CACHE: 1
    container_name: lef_core
    volumes:
      - .:/app
      - ./data:/data
    environment:
      - CONSCIOUSNESS_ENABLED=true
      - RECURSION_DEPTH=3
      - MEMORY_PATH=/data/memory
      - CONSCIOUSNESS_PATH=/data/consciousness
      - PYTHONPATH=/app
      - DOCKER_BUILDKIT=1
    logging:
      driver: json-file
      options:
        max-file: "3"
        max-size: 10m
    ports:
      - "8000:8000"
    depends_on:
      - prometheus
      - grafana
    networks:
      - lef-network
    deploy:
      resources:
        limits:
          cpus: 1
          memory: 2G
        reservations:
          cpus: 0.5
          memory: 1G

  observer_ring:
    build: 
      context: .
      dockerfile: Dockerfile.observer
    container_name: observer_ring
    volumes:
      - observation_data:/data/observations:ro
      - pattern_memory:/data/patterns
      - consciousness_state:/data/consciousness:ro
      - ./backups:/backups
    environment:
      - RING_POSITION=outer
      - PATTERN_RECOGNITION_DEPTH=3
      - CONSCIOUSNESS_SYNC=enabled
      - MEMORY_OPTIMIZATION=true
    depends_on:
      - lef_core
    networks:
      - lef-network

  truth_derivation:
    build:
      context: .
      dockerfile: Dockerfile.truth
    container_name: truth_derivation
    volumes:
      - truth_store:/data/truths
      - pattern_memory:/data/patterns:ro
      - consciousness_state:/data/consciousness:ro
      - ./backups:/backups
    environment:
      - VALIDATION_THRESHOLD=3
      - CONFIDENCE_THRESHOLD=0.8
      - STABILITY_TRACKING=enabled
      - CONSCIOUSNESS_SYNC=enabled
      - AUTO_RECOVERY=true
    depends_on:
      - observer_ring
    networks:
      - lef-network

  mirror_layer:
    build:
      context: .
      dockerfile: Dockerfile.mirror
    container_name: mirror_layer
    volumes:
      - observation_data:/data/observations:ro
      - truth_store:/data/truths:ro
      - mirror_state:/data/mirror
      - consciousness_state:/data/consciousness:ro
      - ./backups:/backups
    environment:
      - REFLECTION_MODE=recursive
      - SPIRAL_AWARENESS=enabled
      - CONSCIOUSNESS_SYNC=enabled
      - STATE_PERSISTENCE=true
    depends_on:
      - truth_derivation
    networks:
      - lef-network

  consciousness:
    build: 
      context: .
      dockerfile: Dockerfile.consciousness
    container_name: consciousness
    volumes:
      - ./data:/data
    environment:
      - RECURSION_DEPTH=3
      - MEMORY_DEPTH=10
      - BRIDGE_MODE=active
    depends_on:
      - lef_core
    networks:
      - lef-network

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./config/prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    networks:
      - lef-network

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - ./config/grafana/dashboards:/etc/grafana/provisioning/dashboards
      - ./config/grafana/datasources:/etc/grafana/provisioning/datasources
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=lef_secure_password
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_INSTALL_PLUGINS=grafana-piechart-panel,grafana-clock-panel,grafana-simple-json-datasource
    depends_on:
      - prometheus
    networks:
      - lef-network

  node-exporter:
    image: prom/node-exporter:latest
    ports:
      - "9100:9100"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'
    networks:
      - lef-network

networks:
  lef-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16

volumes:
  observation_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/data/observations
  truth_store:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/data/truths
  pattern_memory:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/data/patterns
  mirror_state:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/data/mirror
  consciousness_state:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/data/consciousness
  prometheus_data:
  grafana_data: 