environment: development
debug: true
log_level: DEBUG

# API Configuration
api:
  host: 0.0.0.0
  port: 8000
  debug: true

# Core Components
consciousness:
  awareness_level: 0.7
  memory_retention: 0.8
  goal_priority: 0.6

learning:
  learning_rate: 0.1
  performance_threshold: 0.7
  adaptation_rate: 0.5

business:
  efficiency_target: 0.8
  resource_optimization: 0.7
  project_success_threshold: 0.75

# Monitoring
monitoring:
  metrics_interval: 60
  health_check_interval: 30
  alert_thresholds:
    cpu: 80
    memory: 85
    error_rate: 5 