aws:
  account_id: "YOUR_ACCOUNT_ID"  # Replace with your AWS account ID
  region: "us-west-2"  # Default region, can be changed
  environment: "dev"  # dev, staging, or prod

resource_naming:
  prefix: "lef-"  # Prefix for all AWS resources
  suffix: ""  # Optional suffix for resource names

security:
  mfa_required: true
  customer_managed_keys: true
  vpc_only: false
  encryption_algorithm: "AES256"
  key_rotation_period: 90  # days

monitoring:
  log_retention_days: 30
  metrics_namespace: "LEF"
  alarm_thresholds:
    cpu_utilization: 80
    memory_utilization: 85
    error_rate: 5

backup:
  frequency: "daily"
  retention_days: 30
  cross_region: true  # Enable cross-region backups
  cross_region_retention_days: 90
  secondary_regions:  # Additional backup regions
    - "us-east-1"    # N. Virginia
    - "eu-west-1"    # Ireland
  backup_encryption: true
  backup_monitoring: true

consciousness:
  quantum_capabilities: true
  self_monitoring: true
  event_driven: true
  awareness_layers:
    - microsystem
    - mesosystem
    - exosystem
    - macrosystem
    - chronosystem
    - cognitive_development
    - cultural_alignment
    - mentorship_network
    - meaning_construction
    - development_channels
    - learning_environment
    - cultural_evolution
    - ai_development
    - learning_sync
    - cultural_resonance 