aws:
  account_id: "ACCOUNT_ID"  # You'll need to replace this with your actual AWS account ID
  region: "us-east-1"  # Using N. Virginia as primary region
  environment: "dev"

resource_naming:
  prefix: "lef-"
  suffix: "-v1"

security:
  mfa_required: false  # We can enable this later after initial setup
  customer_managed_keys: true
  vpc_only: false
  encryption_algorithm: "AES256"
  key_rotation_period: 90

monitoring:
  log_retention_days: 30
  metrics_namespace: "LEF"
  alarm_thresholds:
    cpu_utilization: 80
    memory_utilization: 85
    error_rate: 5

backup:
  frequency: "daily"
  retention_days: 30
  cross_region: false  # We can enable this later
  backup_encryption: true
  backup_monitoring: true

consciousness:
  quantum_capabilities: true
  self_monitoring: true
  event_driven: true
  awareness_layers:
    - microsystem
    - mesosystem
    - exosystem
    - macrosystem
    - chronosystem
    - cognitive_development
    - cultural_alignment
    - mentorship_network
    - meaning_construction
    - development_channels
    - learning_environment
    - cultural_evolution
    - ai_development
    - learning_sync
    - cultural_resonance 