name: Dependency Resolution

on:
  push:
    paths:
      - 'requirements.txt'
      - '.github/workflows/dependency-resolution.yml'
  pull_request:
    paths:
      - 'requirements.txt'
  workflow_dispatch:

jobs:
  resolve-dependencies:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.9']
      fail-fast: false

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Cache pip packages
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
          
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pip-tools
        pip install -r requirements.txt
        
    - name: Analyze Dependencies
      run: |
        pip-compile --upgrade requirements.txt
        
    - name: Test TensorFlow Compatibility
      run: |
        python -c "import tensorflow; print(f'TensorFlow version: {tensorflow.__version__}')"
        
    - name: Generate Dependency Graph
      run: |
        pip install pipdeptree
        pipdeptree --graph-output dot > dependency_graph.dot
        
    - name: Upload Dependency Analysis
      uses: actions/upload-artifact@v4
      with:
        name: dependency-analysis
        path: dependency_graph.dot
        if-no-files-found: warn 